name: test          # ワークフローの名前

on: push            # push されたら動く

jobs:
  test:
    runs-on: ubuntu-latest   # Ubuntu 上で実行

    steps:
      - uses: actions/checkout@v3   # リポジトリをチェックアウト

      - name: All test              # 好きな名前でOK
        run: bash -xv ./test.bash   # さっき作ったテストスクリプトを実行

